# Generated by Django 2.2.6 on 2019-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informational_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('random1', 'Random1'), ('random2', 'Random2'), ('other', 'Other')], db_index=True, max_length=255),
        ),
    ]
